# Generated by Django 5.1.7 on 2025-03-29 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.IntegerField(choices=[(0, 'Unpaid'), (1, 'Paid')], default=0)),
                ('max_leaves', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Deactive')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('unit', models.IntegerField(choices=[(0, 'Hour'), (1, 'Day')], default=1)),
                ('status', models.IntegerField(choices=[(0, 'Approved'), (1, 'Pending')], default=1)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('approved_time', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leave.leavetype')),
            ],
        ),
    ]
