# Generated by Django 5.1.7 on 2025-04-02 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 12, 42, 50, 58667, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 12, 42, 55, 643152, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Approved'), (1, 'Pending'), (2, 'Rejected')], default=1),
        ),
    ]
