# Generated by Django 5.1.7 on 2025-04-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='for_month',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
