# Generated by Django 5.1.7 on 2025-04-04 06:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_monthlysalary_for_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
